### ISSUE TITLE
Expected type graph.Graph but get graph.HeteroGraph

### ISSUE THREAD

**Issue by xing969541** [awslabs/dgl-ke#211]
Hello, I trying to train dglke according to the examples:

> dglke_train --model_name TransE_l2 --dataset FB15k --batch_size 1000 --neg_sample_size 200 --hidden_dim 400 --gamma 19.9 --lr 0.25 --max_step 500 --log_interval 100 --batch_size_eval 16 -adv --regularization_coef 1.00E-09 --test --num_thread 1 --num_proc 8

and get following error:

> Traceback (most recent call last):
>   File "c:\programdata\anaconda3\envs\dgl\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\programdata\anaconda3\envs\dgl\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\ProgramData\Anaconda3\envs\dgl\Scripts\dglke_train.exe\__main__.py", line 7, in <module>
>   File "c:\programdata\anaconda3\envs\dgl\lib\site-packages\dglke\train.py", line 125, in main
>     rank=i)
>   File "c:\programdata\anaconda3\envs\dgl\lib\site-packages\dglke\dataloader\sampler.py", line 389, in create_sampler
>     return_false_neg=False)
>   File "c:\programdata\anaconda3\envs\dgl\lib\site-packages\dgl\contrib\sampling\sampler.py", line 694, in __init__
>     self._chunk_size)
>   File "c:\programdata\anaconda3\envs\dgl\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 190, in __call__
>     ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
>   File "c:\programdata\anaconda3\envs\dgl\lib\site-packages\dgl\_ffi\base.py", line 64, in check_call
>     raise DGLError(py_str(_LIB.DGLGetLastError()))
> dgl._ffi.base.DGLError: [10:33:11] C:\Users\Administrator\dgl-0.5\include\dgl/packed_func_ext.h:117: Check failed: ObjectTypeChecker<TObjectRef>::Check(sptr.get()): Expected type graph.Graph but get graph.HeteroGraph

It's running on python 3.6, windows10. Relevant package versions:

> -dgl==0.6.0post1
> -dglke==0.1.2
> -pytorch==1.8.0

Thanks for any help!

**Comment by JiaquanYe** [comment]
I have got the same error, too...

**Comment by zheng-da** [comment]
DGL-KE works with DGL 0.4

**Comment by JonnyTran** [comment]
> DGL-KE works with DGL 0.4

Is there a way to add support for DGLHeteroGraph? Please consider, as it is an important feature.

**Comment by classicsong** [comment]
We are going to update DGL-KE to work with DGL 0.7. Then DGLHeteroGraph will be supported.

**Comment by liuhuanyong** [comment]
> > DGL-KE works with DGL 0.4


TypeError: __init__() got an unexpected keyword argument 'chunk_size'
